// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import Carousel from 'stimulus-carousel'

// import CarouselController from "./carousel_controller"
// application.register("carousel", CarouselController)

// const application = Application.start()
application.register('carousel', Carousel)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import Popover from 'stimulus-popover'
application.register('popover', Popover)
